//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public string ManagerID { get; set; }
        public string Name { get; set; }
        public string DeptID { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
