//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TimeSheet
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Database1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Database1Entities object using the connection string found in the 'Database1Entities' section of the application configuration file.
        /// </summary>
        public Database1Entities() : base("name=Database1Entities", "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(string connectionString) : base(connectionString, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(EntityConnection connection) : base(connection, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Activities> Activities
        {
            get
            {
                if ((_Activities == null))
                {
                    _Activities = base.CreateObjectSet<Activities>("Activities");
                }
                return _Activities;
            }
        }
        private ObjectSet<Activities> _Activities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dept> Dept
        {
            get
            {
                if ((_Dept == null))
                {
                    _Dept = base.CreateObjectSet<Dept>("Dept");
                }
                return _Dept;
            }
        }
        private ObjectSet<Dept> _Dept;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Divisions> Divisions
        {
            get
            {
                if ((_Divisions == null))
                {
                    _Divisions = base.CreateObjectSet<Divisions>("Divisions");
                }
                return _Divisions;
            }
        }
        private ObjectSet<Divisions> _Divisions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Projects> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Projects>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Projects> _Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Timesheets> Timesheets
        {
            get
            {
                if ((_Timesheets == null))
                {
                    _Timesheets = base.CreateObjectSet<Timesheets>("Timesheets");
                }
                return _Timesheets;
            }
        }
        private ObjectSet<Timesheets> _Timesheets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Activities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActivities(Activities activities)
        {
            base.AddObject("Activities", activities);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dept EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDept(Dept dept)
        {
            base.AddObject("Dept", dept);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Divisions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDivisions(Divisions divisions)
        {
            base.AddObject("Divisions", divisions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Projects projects)
        {
            base.AddObject("Projects", projects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Timesheets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimesheets(Timesheets timesheets)
        {
            base.AddObject("Timesheets", timesheets);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Activities")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Activities : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Activities object.
        /// </summary>
        /// <param name="managerID">Initial value of the ManagerID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Activities CreateActivities(global::System.String managerID, global::System.String name)
        {
            Activities activities = new Activities();
            activities.ManagerID = managerID;
            activities.Name = name;
            return activities;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerID
        {
            get
            {
                return _ManagerID;
            }
            set
            {
                if (_ManagerID != value)
                {
                    OnManagerIDChanging(value);
                    ReportPropertyChanging("ManagerID");
                    _ManagerID = StructuralObject.SetValidValue(value, false, "ManagerID");
                    ReportPropertyChanged("ManagerID");
                    OnManagerIDChanged();
                }
            }
        }
        private global::System.String _ManagerID;
        partial void OnManagerIDChanging(global::System.String value);
        partial void OnManagerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeptID
        {
            get
            {
                return _DeptID;
            }
            set
            {
                OnDeptIDChanging(value);
                ReportPropertyChanging("DeptID");
                _DeptID = StructuralObject.SetValidValue(value, true, "DeptID");
                ReportPropertyChanged("DeptID");
                OnDeptIDChanged();
            }
        }
        private global::System.String _DeptID;
        partial void OnDeptIDChanging(global::System.String value);
        partial void OnDeptIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Dept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dept : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dept object.
        /// </summary>
        /// <param name="managerID">Initial value of the ManagerID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="deptID">Initial value of the DeptID property.</param>
        /// <param name="divisionID">Initial value of the DivisionID property.</param>
        public static Dept CreateDept(global::System.String managerID, global::System.String name, global::System.String deptID, global::System.String divisionID)
        {
            Dept dept = new Dept();
            dept.ManagerID = managerID;
            dept.Name = name;
            dept.DeptID = deptID;
            dept.DivisionID = divisionID;
            return dept;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerID
        {
            get
            {
                return _ManagerID;
            }
            set
            {
                if (_ManagerID != value)
                {
                    OnManagerIDChanging(value);
                    ReportPropertyChanging("ManagerID");
                    _ManagerID = StructuralObject.SetValidValue(value, false, "ManagerID");
                    ReportPropertyChanged("ManagerID");
                    OnManagerIDChanged();
                }
            }
        }
        private global::System.String _ManagerID;
        partial void OnManagerIDChanging(global::System.String value);
        partial void OnManagerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeptID
        {
            get
            {
                return _DeptID;
            }
            set
            {
                OnDeptIDChanging(value);
                ReportPropertyChanging("DeptID");
                _DeptID = StructuralObject.SetValidValue(value, false, "DeptID");
                ReportPropertyChanged("DeptID");
                OnDeptIDChanged();
            }
        }
        private global::System.String _DeptID;
        partial void OnDeptIDChanging(global::System.String value);
        partial void OnDeptIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DivisionID
        {
            get
            {
                return _DivisionID;
            }
            set
            {
                OnDivisionIDChanging(value);
                ReportPropertyChanging("DivisionID");
                _DivisionID = StructuralObject.SetValidValue(value, false, "DivisionID");
                ReportPropertyChanged("DivisionID");
                OnDivisionIDChanged();
            }
        }
        private global::System.String _DivisionID;
        partial void OnDivisionIDChanging(global::System.String value);
        partial void OnDivisionIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Divisions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Divisions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Divisions object.
        /// </summary>
        /// <param name="managerID">Initial value of the ManagerID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="divisionID">Initial value of the DivisionID property.</param>
        public static Divisions CreateDivisions(global::System.String managerID, global::System.String name, global::System.String divisionID)
        {
            Divisions divisions = new Divisions();
            divisions.ManagerID = managerID;
            divisions.Name = name;
            divisions.DivisionID = divisionID;
            return divisions;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerID
        {
            get
            {
                return _ManagerID;
            }
            set
            {
                if (_ManagerID != value)
                {
                    OnManagerIDChanging(value);
                    ReportPropertyChanging("ManagerID");
                    _ManagerID = StructuralObject.SetValidValue(value, false, "ManagerID");
                    ReportPropertyChanged("ManagerID");
                    OnManagerIDChanged();
                }
            }
        }
        private global::System.String _ManagerID;
        partial void OnManagerIDChanging(global::System.String value);
        partial void OnManagerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DivisionID
        {
            get
            {
                return _DivisionID;
            }
            set
            {
                OnDivisionIDChanging(value);
                ReportPropertyChanging("DivisionID");
                _DivisionID = StructuralObject.SetValidValue(value, false, "DivisionID");
                ReportPropertyChanged("DivisionID");
                OnDivisionIDChanged();
            }
        }
        private global::System.String _DivisionID;
        partial void OnDivisionIDChanging(global::System.String value);
        partial void OnDivisionIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Projects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Projects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Projects object.
        /// </summary>
        /// <param name="managerID">Initial value of the ManagerID property.</param>
        public static Projects CreateProjects(global::System.String managerID)
        {
            Projects projects = new Projects();
            projects.ManagerID = managerID;
            return projects;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerID
        {
            get
            {
                return _ManagerID;
            }
            set
            {
                if (_ManagerID != value)
                {
                    OnManagerIDChanging(value);
                    ReportPropertyChanging("ManagerID");
                    _ManagerID = StructuralObject.SetValidValue(value, false, "ManagerID");
                    ReportPropertyChanged("ManagerID");
                    OnManagerIDChanged();
                }
            }
        }
        private global::System.String _ManagerID;
        partial void OnManagerIDChanging(global::System.String value);
        partial void OnManagerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Client_name
        {
            get
            {
                return _Client_name;
            }
            set
            {
                OnClient_nameChanging(value);
                ReportPropertyChanging("Client_name");
                _Client_name = StructuralObject.SetValidValue(value, true, "Client_name");
                ReportPropertyChanged("Client_name");
                OnClient_nameChanged();
            }
        }
        private global::System.String _Client_name;
        partial void OnClient_nameChanging(global::System.String value);
        partial void OnClient_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Proj_name
        {
            get
            {
                return _Proj_name;
            }
            set
            {
                OnProj_nameChanging(value);
                ReportPropertyChanging("Proj_name");
                _Proj_name = StructuralObject.SetValidValue(value, true, "Proj_name");
                ReportPropertyChanged("Proj_name");
                OnProj_nameChanged();
            }
        }
        private global::System.String _Proj_name;
        partial void OnProj_nameChanging(global::System.String value);
        partial void OnProj_nameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Timesheets")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Timesheets : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Timesheets object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="start_time">Initial value of the Start_time property.</param>
        /// <param name="finish_time">Initial value of the Finish_time property.</param>
        /// <param name="activity">Initial value of the Activity property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static Timesheets CreateTimesheets(global::System.Int32 id, global::System.TimeSpan date, global::System.Int32 start_time, global::System.Int32 finish_time, global::System.String activity, global::System.String status)
        {
            Timesheets timesheets = new Timesheets();
            timesheets.Id = id;
            timesheets.Date = date;
            timesheets.Start_time = start_time;
            timesheets.Finish_time = finish_time;
            timesheets.Activity = activity;
            timesheets.Status = status;
            return timesheets;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.TimeSpan _Date;
        partial void OnDateChanging(global::System.TimeSpan value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Start_time
        {
            get
            {
                return _Start_time;
            }
            set
            {
                OnStart_timeChanging(value);
                ReportPropertyChanging("Start_time");
                _Start_time = StructuralObject.SetValidValue(value, "Start_time");
                ReportPropertyChanged("Start_time");
                OnStart_timeChanged();
            }
        }
        private global::System.Int32 _Start_time;
        partial void OnStart_timeChanging(global::System.Int32 value);
        partial void OnStart_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Finish_time
        {
            get
            {
                return _Finish_time;
            }
            set
            {
                OnFinish_timeChanging(value);
                ReportPropertyChanging("Finish_time");
                _Finish_time = StructuralObject.SetValidValue(value, "Finish_time");
                ReportPropertyChanged("Finish_time");
                OnFinish_timeChanged();
            }
        }
        private global::System.Int32 _Finish_time;
        partial void OnFinish_timeChanging(global::System.Int32 value);
        partial void OnFinish_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Activity
        {
            get
            {
                return _Activity;
            }
            set
            {
                OnActivityChanging(value);
                ReportPropertyChanging("Activity");
                _Activity = StructuralObject.SetValidValue(value, false, "Activity");
                ReportPropertyChanged("Activity");
                OnActivityChanged();
            }
        }
        private global::System.String _Activity;
        partial void OnActivityChanging(global::System.String value);
        partial void OnActivityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="first_name">Initial value of the First_name property.</param>
        /// <param name="last_name">Initial value of the Last_name property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="job">Initial value of the Job property.</param>
        /// <param name="mail">Initial value of the Mail property.</param>
        public static Users CreateUsers(global::System.String id, global::System.String first_name, global::System.String last_name, global::System.String password, global::System.String job, global::System.String mail)
        {
            Users users = new Users();
            users.ID = id;
            users.First_name = first_name;
            users.Last_name = last_name;
            users.Password = password;
            users.Job = job;
            users.Mail = mail;
            return users;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_name
        {
            get
            {
                return _First_name;
            }
            set
            {
                OnFirst_nameChanging(value);
                ReportPropertyChanging("First_name");
                _First_name = StructuralObject.SetValidValue(value, false, "First_name");
                ReportPropertyChanged("First_name");
                OnFirst_nameChanged();
            }
        }
        private global::System.String _First_name;
        partial void OnFirst_nameChanging(global::System.String value);
        partial void OnFirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_name
        {
            get
            {
                return _Last_name;
            }
            set
            {
                OnLast_nameChanging(value);
                ReportPropertyChanging("Last_name");
                _Last_name = StructuralObject.SetValidValue(value, false, "Last_name");
                ReportPropertyChanged("Last_name");
                OnLast_nameChanged();
            }
        }
        private global::System.String _Last_name;
        partial void OnLast_nameChanging(global::System.String value);
        partial void OnLast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Job
        {
            get
            {
                return _Job;
            }
            set
            {
                OnJobChanging(value);
                ReportPropertyChanging("Job");
                _Job = StructuralObject.SetValidValue(value, false, "Job");
                ReportPropertyChanged("Job");
                OnJobChanged();
            }
        }
        private global::System.String _Job;
        partial void OnJobChanging(global::System.String value);
        partial void OnJobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, false, "Mail");
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeptID
        {
            get
            {
                return _DeptID;
            }
            set
            {
                OnDeptIDChanging(value);
                ReportPropertyChanging("DeptID");
                _DeptID = StructuralObject.SetValidValue(value, true, "DeptID");
                ReportPropertyChanged("DeptID");
                OnDeptIDChanged();
            }
        }
        private global::System.String _DeptID;
        partial void OnDeptIDChanging(global::System.String value);
        partial void OnDeptIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Proj_name
        {
            get
            {
                return _Proj_name;
            }
            set
            {
                OnProj_nameChanging(value);
                ReportPropertyChanging("Proj_name");
                _Proj_name = StructuralObject.SetValidValue(value, true, "Proj_name");
                ReportPropertyChanged("Proj_name");
                OnProj_nameChanged();
            }
        }
        private global::System.String _Proj_name;
        partial void OnProj_nameChanging(global::System.String value);
        partial void OnProj_nameChanged();

        #endregion

    }

    #endregion

}
