//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheets
    {
        public int Id { get; set; }
        public System.TimeSpan Date { get; set; }
        public int Start_time { get; set; }
        public int Finish_time { get; set; }
        public string Activity { get; set; }
        public string Status { get; set; }
    }
}
