//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheets
    {
        public string Start_time { get; set; }
        public string Finish_time { get; set; }
        public string Activity { get; set; }
        public string UserID { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public int ID { get; set; }
    }
}
